//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChenkaCoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableSits
    {
        public int SitId { get; set; }
        public int tableId { get; set; }
        public byte available { get; set; }
    }
}
